Repository MichelFR/MqDockerUp, pull requests merged in 2023-04, with the labels that each got.

#41 Small readability/formatting improvements
  src/services/HomeassistantService.ts
Labels: refactoring

#47 0.15.0
  package.json
Labels: ignore-for-release

#50 Fix build-error
  package.json
  src/services/HomeassistantService.ts
Labels: issue:bug, fix

#51 Add support for more architectures
  .github/workflows/docker-image.yml
  package.json
Labels: enhancement

#52 remove armv6
  .github/workflows/docker-image.yml
Labels: fix

#56 feat(getDockerHubUrl): support official library images in API URL generation
  package.json
  src/services/DockerService.ts
Labels: enhancement
